Allow raytracing for scene capture components
around-media/ue4-fork-4.24 pull request #2
Opened 2020-01-23 13:29 UTC by michielvandencamparound

2020-01-23 13:37 UTC, etiennebeaucheminp-prompto commented
@michielvandencamparound could you put some link where you found the information to do such a fix in comments in the code and/or in the pull request?

The changes itself looks fine, but it is a bit suspicious that we can just remove an if like that in the engine, so having some further explanation would be useful.

2020-01-23 13:38 UTC, etiennebeaucheminp-prompto requested changes
@michielvandencamparound could you put some link where you found the information to do such a fix in comments in the code and/or in the pull request?

The changes itself looks fine, but it is a bit suspicious that we can just remove an if like that in the engine, so having some further explanation would be useful.

2020-01-23 14:04 UTC, michielvandencamparound commented
@etiennebeaucheminp-prompto I added a description in the pull request (I think the info is not relevant enough to put into the code)

2020-01-23 14:24 UTC, etiennebeaucheminp-prompto approved these changes

2020-01-24 07:53 UTC, ShadeInteractive approved these changes

2020-01-24 09:40 UTC, merged